name: MuleSoft CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java (Mule 4 supports Java 8/11/17 depending on runtime)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # Build + Run MUnit tests
      - name: Build and run MUnit tests
        run: |
          mvn -B clean test \
            -Dmule.env=ci

      # Package Mule application
      - name: Package Mule application
        run: |
          mvn -B package -DskipTests

      # Upload artifact (JAR)
      - name: Upload Mule artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-application
          path: target/*.jar
      - name: Deploy Mule application to CloudHub 2.0
        run: |
          mvn clean package -Pcloudhub-2.0 \
            -DmuleDeploy \
            -DskipTests \
            -Danypoint.client_id=${{ secrets.ANYPOINT_CLIENT_ID }} \
            -Danypoint.client_secret=${{ secrets.ANYPOINT_CLIENT_SECRET }} \
            -Danypoint.env=Sandbox \
            -Danypoint.org=c39dc6dd-e124-4390-867b-7b58e9d44727

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: mule-application

    - name: Deploy to CloudHub
      env:
        ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
      run: |
        artifactName=mule-application.jar
        mvn mule:deploy \
        -DmuleDeploy \
        -Dartifact=$artifactName \
        -Dusername="mani_jab26" \
        -Dpassword="Mani@123456" \
        -Denvironment="Sandbox" \
        -Dregion="us-east-1" \
        -Dworkers="1" \
        -DworkerType="MICRO" \
        -DapplicationName="demo1"
